en_cn = {
    'accessory': '饰品',
    'mana': '法力',
    'mana cost': '法力消耗',
    'projectile': '投射物',
    'speed': '速度',
    'damage': '伤害',
    'knockback': '击退',
    'physical': '物理',
    'piercing': '穿透',
    'magical': '魔法',
    'melee': '近战',
    'ranged': '远程',
    'defense': '防御',
    'sec': '秒',
    'regeneration': '恢复',
    'touching': '接触',
    'night vision': '夜视',

    'ingot': '锭',
    'substance': '物质',
    'core': '核心',
    'mark': '印记',

    'wood': '木材',
    'wooden': '木',
    'leaf': '叶子',
    'copper': '铜',
    'iron': '铁',
    'steel': '钢',
    'platinum': '铂金',
    'cell organization': '细胞组织',
    'magic stone': '魔石',
    'blood': '血',
    'firite': '浴火',
    'mysterious': '神秘',
    'storm': '风暴',
    'soul': '灵魂',
    'evil': '邪恶',
    'soul of flying': '飞行之魂',
    'palladium': '钯金',
    'mithrill': '秘银',
    'titanium': '钛金',

    'torch': '火炬',
    'night visioner': '夜视仪',
    'hammer': '锤',
    'furnace': '熔炉',
    'anvil': '铁砧',
    'shield': '盾牌',
    'bottle': '瓶',
    'necklace': '项链',

    'sword': '剑',
    'blade': '刃',
    'magic_sword': '魔剑',
    'magic_blade': '魔刃',
    'bloody': '血腥',
    'volcano': '火山',
    'sand': '沙',
    'night\'s edge': '永夜刃',
    'spiritual': '灵魂',
    'stabber': '刺探者',
    'balanced': '平衡',
    'bow': '弓',
    'recurve bow': '反曲弓',
    'piercer': '穿刺者',
    'discord storm': '混乱风暴',
    'pistol': '手枪',
    'rifle': '步枪',
    'submachine gun': '霰弹枪',
    'magma': '熔岩',
    'assaulter': '突击者',
    'shadow': '影',
    'arrow': '箭',
    'magic': '魔',
    'bullet': '子弹',
    'plasma': '脑浆',
    'rock': '岩石',
    'shadow bullet': '暗影子弹',
    'glowing splint': '火花木棒',
    'wand': '魔杖',
    'burning book': '燃烧之书',
    'talent book': '天赋之书',
    'hematology': '血液学',
    'midnight\'s wand': '午夜魔杖',
    'destroyer': '毁灭者',
    'daedalus': '代达罗斯',
    'stormbow': '风暴弓',
    'true': '真',
    'excalibur': '圣剑',
    'gun': '枪',
    'quick': '迅捷',
    'dangerous': '危险',
    'terrified': '恐惧',
    'sheath': '剑鞘',
    'quiver': '箭袋',
    'hat': '帽子',
    'helmet': '头盔',
    'cloak': '披风',
    'pluvial': '斗篷',
    'ring': '戒指',
    'orange': '橙色',
    'yellow': '黄色',
    'green': '绿色',
    'blue': '蓝色',
    'purple': '紫色',
    'red': '红色',
    'cyan': '青色',
    'aimer': '瞄准者',
    'windstorm': '风暴',
    'winds': '风',
    '\'s': '',
    '\'': '',
    'swordman': '剑士',
    'assassin': '刺客',
    'warlock': '术士',
    'paladin': '圣骑士',
    'wings': '翅膀',
    'honest flyer': '诚实的飞行者',
    'crabapple': '螃果',
    'butterscotch pie': '奶油肉桂派',
    'seatea': '海茶',
    'heart': '心',
    'crystal': '水晶',

    'can only be placed in the first slot': '只能放在第一饰品栏',
    'can only be placed in the second slot': '只能放在第二饰品栏',
}